### ISSUE TITLE
Nice plugin, just missing the grouped resources

### ISSUE THREAD

**Issue by ignaciotcrespo** [mistamek/Android-drawable-preview-plugin#1]
Love this plugin, good idea! And the source is minimal, good job

The only missing thing is to show the icon in the grouped resources

![image](https://user-images.githubusercontent.com/6496116/40260557-b2a02a62-5ad1-11e8-8d66-c7a985a9281f.png)

it shows a folder icon, needing to open the folder to see the new drawable icons.

**Comment by mistamek** [comment]
Hi Ignacio, thanks for idea, i will try to add this feature in the next release.

**Comment by mistamek** [comment]
After checking how android project view working, unfortunately, I can tell that for now it's not possible, at least without some really dirty hacks. Icon for holder inside android project view just hardcoded to be system icon, and right now i don't have time to find stable workaround. Closing for now, but definitely will come back to this problem later.
