### ISSUE TITLE
Incompatible with Android Studio 4.1

### ISSUE THREAD

**Issue by hormesiel** [mistamek/Android-drawable-preview-plugin#14]
Hi, first thanks for this very handy plugin!

Unfortunately it's not compatible with Android Studio 4.1 which was released a few weeks ago :

![image](https://user-images.githubusercontent.com/1585006/96423356-8290f900-11f9-11eb-9707-06b64f6ffa64.png)
![image](https://user-images.githubusercontent.com/1585006/96423631-df8caf00-11f9-11eb-9960-33b9bffc9554.png)

**Comment by mistamek** [comment]
Hi, Mickaël, I fixed the problem. You can download new release from this repository, or wait few days until plugin will be published to marketplace.

**Comment by hormesiel** [comment]
Awesome thank you! I'll wait until the plugin is published on the marketplace and I'll close this issue.

**Comment by julia40124009** [comment]
good job!!

**Comment by mistamek** [comment]
Plugin is now can be downloaded from Android Studio. Can you check and confirme that everything is working?

**Comment by julia40124009** [comment]
working for me ! thanks

**Comment by hormesiel** [comment]
It works! Thank you!
