### ISSUE TITLE
SVG file support 

### ISSUE THREAD

**Issue by vatsaltanna** [mistamek/Android-drawable-preview-plugin#16]
Plugin does not detect svg files for preview in android studio.

**Comment by mistamek** [comment]
Hi Vatsal. Thanks for the feedback. Unfortunately, I don't have time to add this functionality right now. But within a month I will try to add it.

**Comment by mistamek** [comment]
I have added SVG support and uploaded an update. 
Can you check that everything works and close this issue if everything is ok?
