### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by HanderWei** [mistamek/Android-drawable-preview-plugin#4]
I searched for "Android Drawable Preview",  but not found in Android Studio(Mac OS).

The result is only "Android Drawable Viewer".

**Comment by HanderWei** [comment]
And the .zip file isn't work for me.

**Comment by mistamek** [comment]
Hi, thanks for report. What version of studio and Mac OS are you using? You can find this info in help-about section in menu bar.

**Comment by phxnirvana** [comment]
it shows incompatible dialog with .zip and can't be find in the studio
android studio 3.0.1 
macOS10.13.5

**Comment by mistamek** [comment]
Can you try to update studio to latest 3.1.3 ?

**Comment by phxnirvana** [comment]
It works when I updated the studio. Does it only support latest version?

**Comment by mistamek** [comment]
I'm sorry, but currently yes. If will try to lower min version to at least 3.0, but currently it's better to update.
