### ISSUE TITLE
3.1 不能用哦

### ISSUE THREAD

**Issue by KobeBryant824** [mistamek/Android-drawable-preview-plugin#5]
没有效果

**Comment by mistamek** [comment]
Hi, can you provide additional information? Which os you using, which version of Android studio?

**Comment by xzk714** [comment]
@KobeBryant824 如果装了theme插件或者其他能改动改变了图标的需要先把那个关掉或者卸掉

**Comment by xzk714** [comment]
@mistamek The plugin is so cool,sometimes not work if you use some theme plugin.

**Comment by KobeBryant824** [comment]
@xzk714 这就不好了，theme是必须的

**Comment by mistamek** [comment]
Oh I see. And probably know how to fix this, but can you give list of the theme plugins for debug purposes?

**Comment by KobeBryant824** [comment]
@mistamek Material Theme UI

**Comment by mistamek** [comment]
I added ordering for icon provider, so it should work with Material Theme UI from version 2.9.0-pre1
