### ISSUE TITLE
Previews are really small

### ISSUE THREAD

**Issue by percula** [mistamek/Android-drawable-preview-plugin#7]
The previews are very small, see screenshot:

![image](https://user-images.githubusercontent.com/16809252/47296820-6d206e80-d5e1-11e8-9543-8959ff98da19.png)

In the screenshot, they are all xml files but pngs and jpgs are the same size too.

**Comment by mistamek** [comment]
Hi, can you provide additional information? Which os you using, which version of Android studio?

**Comment by percula** [comment]
Hi @mistamek, thanks for this great plugin. I'm using Android Studio 3.2.1 on Mac OS 10.13.6.

**Comment by mistamek** [comment]
Ok, thank you for information, I try to fix this.

**Comment by ganesh2shiv** [comment]
Drawable files icon size is perfect on Windows but is very small on Mac.

**Comment by mistamek** [comment]
Yeah, it happens because of Retina. But unfortunately I don’t know when I can fix it due to the lack of free time and the device for testing. Sorry for this. But you can try to change the value for the size of the icon in Constanst.kt or tweak RetinaImageIcon.kt

**Comment by mistamek** [comment]
Update progress information. Found a way to fix it, in the near future I will make a release.

**Comment by mistamek** [comment]
I increased the size of icons for Retina devices, now the icons will not be so small. Also in Settings - Appeareance and Behavior - Android drawable preview now you can set the size of the icon. The update will be available for download in a few days.

**Comment by percula** [comment]
Just got the update and it works beautifully. Thank you!
