### ISSUE TITLE
Request: handle adaptive-icon

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [mistamek/Android-drawable-preview-plugin#9]
Not shown:

![image](https://user-images.githubusercontent.com/5357526/50312887-6fecf200-04b2-11e9-892f-085b5f465155.png)

**Comment by mistamek** [comment]
Hi, this feature is already implemented, and works with the default icon. Can you provide your icon for debug?

**Comment by AndroidDeveloperLB** [comment]
Attached

[ttt.zip](https://github.com/mistamek/Android-drawable-preview-plugin/files/2706712/ttt.zip)

**Comment by mistamek** [comment]
Hmm, can you try move `<color name="ic_launcher_background">#90CAF9</color>` 
to colors.xml and delete ic_launcher_background.xml? 
I think that the problem is that sdk expects in ic_launcher_background.xml, which lies in the drawables, exactly the drawable, and not the color resource. As soon as I moved this resource to colors.xml, everything worked as expected.

**Comment by AndroidDeveloperLB** [comment]
Why? That's a valid configuration of the icon. I think that's also what the IDE made it.
Look. Even on a completely new project it doesn't handle the adaptive icon :

![image](https://user-images.githubusercontent.com/5357526/50405552-391f2080-07bf-11e9-9ac6-72417f2848d3.png)

**Comment by mistamek** [comment]
Hmm, that's weird. Background seems to have broken. Tomorrow I will try to solve the problem.

**Comment by AndroidDeveloperLB** [comment]
ok please let me know.
It's a cool plugin. Should have been the default behavior, built in the IDE. :)

**Comment by mistamek** [comment]
Fixed a problem. I start parsing the icon only if it lies in the folder with the drawables in the path. Adaptive icon lies in mipmap folder, so parsing was not working. 

But by the way, the resource that you showed is still not working. Studio itself shows that the format is not correct. And openapi that I using cannot parse this file.
![screenshot_1](https://user-images.githubusercontent.com/37661013/50417835-850eab80-0839-11e9-8bd5-20eb99e9a4c6.png)

**Comment by AndroidDeveloperLB** [comment]
Maybe you should update your IDE version. Try Canary.
For me it worked fine.

**Comment by mistamek** [comment]
Tried to use canary 3.4 still does not help. And now prints `Android resource linking failed` when building the project. Anyway mipmaps now working fine :)

**Comment by AndroidDeveloperLB** [comment]
Have you published a new version of the plugin? I don't see any new update fixing the issue. Using v 1.1.3.
Attached a sample project with this icons.
It works fine for me on the preview, but not on the file icon.

![image](https://user-images.githubusercontent.com/5357526/50426707-cafd5b00-089d-11e9-9dce-14ccd9931a1f.png)

![image](https://user-images.githubusercontent.com/5357526/50426716-e8322980-089d-11e9-89cd-3179d0a258aa.png)


[LwpBug.zip](https://github.com/mistamek/Android-drawable-preview-plugin/files/2709052/LwpBug.zip)

**Comment by mistamek** [comment]
Yep, version 1.1.4 pending approval, and will be available for download within few days.
![screenshot_1](https://user-images.githubusercontent.com/37661013/50481753-67d20c80-09f4-11e9-8a51-9ec14c23a088.png)

**Comment by AndroidDeveloperLB** [comment]
Can you please let it opened till I confirm it's ok?

**Comment by mistamek** [comment]
Sure, btw you can try install plugin manually by following instruction in readme.

**Comment by AndroidDeveloperLB** [comment]
Seems to work fine now.
Thank you.
I haven't checked, but assets are working fine too, right?

**Comment by mistamek** [comment]
Assets should work fine with binary files, but xml will not work.

**Comment by AndroidDeveloperLB** [comment]
xml can be used in assets folder by the app? I don't think it's needed by the plugin, if it's not possible to use them anyway...
You mean vectorDrawable or other kinds, or all kinds?

**Comment by mistamek** [comment]
Exactly, thats why I don't added this support.
Not sure about vectors, but other drawables will not render 100%.

**Comment by AndroidDeveloperLB** [comment]
I see. Maybe there is a way, but I don't see much of a point to do it using assets folder. 
It could be nice if the plugin had it, but I don't think it serves much purpose.
